### ISSUE TITLE
Code Published?

### ISSUE THREAD

**Issue by 0xABCDE** [jcomas/AirQualityMeter#1]
Hi, have you published any code in the Github? I am really interested in the M5Stack Core2 code with lvgl integration.

Congrats for the effort!

**Comment by jcomas** [comment]
Not yet but here https://github.com/jcomas/AirQualityMeter/blob/main/docs/examples/lvgl-gui-basic-example.zip you are an example using Visual Studio Code with PlatformIO for M5Stack Core2.

**Comment by 0xABCDE** [comment]
Hi @jcomas Thank you very much for this. Build this in VSCode + PlatformIO and it works like charms! Gave me a kickstart for lvgl integration
